# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
# To deploy locally use serverless deploy --stage dev --region us-east-1

service: TodoApp
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${opt:stage, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  role: arn:aws:iam::627390763742:role/TodoAppLamdbaRole
  stackName: ${self:service}${self:provider.stage}
  apiName: TodoApp ${self:provider.stage}

functions: ${file(./Serverless/functions.yml):functions}

resources: 
  - ${file(./Serverless/dynamodb-resources.yml)}