# Welcome to Serverless!
# To deploy locally use serverless deploy --stage dev --region us-east-1

service: TodoApp

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${opt:stage, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  role: arn:aws:iam::627390763742:role/TodoAppLamdbaRole
  stackName: ${self:service}${self:provider.stage}
  apiName: TodoApp ${self:provider.stage}

functions: ${file(./Serverless/functions.yml):functions}

resources: 
  - ${file(./Serverless/dynamodb-resources.yml)}